[package]
name = "audiocheckr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
symphonia = { version = "0.5", features = ["all"] }
rustfft = "6.0"
image = "0.24"
imageproc = "0.23"
rusttype = "0.9"
walkdir = "2.3"
colorful = "0.2"

[dependencies.spectrum-analyzer]
version = "1.5"